import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import { Sidebar } from "@/components/sidebar"; // Sidebar'ı import et

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const locale = await getLocale();

   return (
      <html lang={locale} suppressHydrationWarning>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
               <NextIntlClientProvider>
                  <div className="flex min-h-screen w-full">
                     {" "}
                     {/* Flex container */}
                     <Sidebar /> {/* Sidebar'ı ekle */}
                     <main className="flex-1 flex flex-col">
                        {" "}
                        {/* Ana içerik alanı */}
                        {children}
                     </main>
                  </div>
                  <Toaster />
               </NextIntlClientProvider>
            </ThemeProvider>
         </body>
      </html>
   );
}
